# Generated by Django 3.1.3 on 2020-11-03 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('worksheet', '0003_auto_20201103_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('MG', 'Менеджер'), ('DR', 'Водитель'), ('LD', 'Грузчик')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'position': 'Менеджер'}, on_delete=django.db.models.deletion.CASCADE, to='worksheet.employee'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
