# Generated by Django 3.1.3 on 2020-11-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0005_auto_20201103_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='worksheet.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='worksheet.employee'),
        ),
    ]
