# Generated by Django 3.1.3 on 2020-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0006_auto_20201103_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Noname', max_length=30),
        ),
    ]
