# Generated by Django 3.1.3 on 2020-11-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0007_employee_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_created']},
        ),
    ]
