# Generated by Django 3.1.3 on 2020-11-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0010_auto_20201108_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheet.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='worksheet.employee'),
        ),
    ]
