# Generated by Django 3.1.3 on 2020-11-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0014_auto_20201125_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheet.client'),
        ),
    ]
