# Generated by Django 3.1.3 on 2020-11-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0015_employee_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='clients',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheet.employee'),
        ),
    ]
