# Generated by Django 3.1.3 on 2020-11-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0016_auto_20201126_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='task',
            name='driver',
        ),
    ]
