# Generated by Django 3.1.3 on 2020-11-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0017_auto_20201126_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phoneNumber',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='building',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
