# Generated by Django 3.1.3 on 2020-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0018_auto_20201130_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
