# Generated by Django 3.1.3 on 2020-12-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0019_auto_20201201_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
