# Generated by Django 3.1.3 on 2020-12-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0022_auto_20201209_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='coordinates',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
